name: Alerta CI DevOps

on:
  push:
    branches:
      - main

jobs:
  notificar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Ejecutar Hola Mundo
        run: node index.js

      - name: Enviar notificación a ntfy
        run: |
          curl -H "Title: Nuevo Push en main" \
               -H "Priority: high" \
               -d "Se ha subido código al repositorio en la rama main por Tomas Alvarez 2023-1023." \
               https://ntfy.sh/devops-itla
